version: '3.7'
services:
  postgres:
    image: postgres:11.1
    restart: always
    volumes:
      - ./docker_config/db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./docker_config/db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hotel_2
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - iqs_net
  app:
    build: ./docker_config/app/
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - iqs_net
volumes:
  postgres-data:

networks:
  iqs_net:
    name: "iqs_net"


