version: '3.7'
services:
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hotel_2
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - iqs_net
  app:
    build: .
    image: hotel-reservation
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - iqs_net

networks:
  iqs_net:
    name: "iqs_net"


